<h1>Books in cart</h1>

<?php if (!$books) : ?>

    Empty :(

<?php else:?>

    <?php foreach ($books as $book) : ?>
        Title:  <?=$book['title']?><br>
        Price:  <?=$book['price']?><br>
        id:  <?=$book['id']?><br>
        <a href="/delete/<?=$book['id']?>">Remove from cart</a>
        <hr>
    <?php endforeach; ?>

<?php endif;?>
<hr>
<a href="/remove">Remove all from cart</a>     <a href="#">Buy</a>
