<b>This is contact action of index controller</b><br>

<b><?= Session::getFlash(); ?></b>
<table>
<form method="post">
    <tr>
        <td>Username: </td>
        <td><input type="text" name="username" value="<?= $form->username?>"></td>
    </tr>
    <tr>
        <td>Email:</td>
        <td><input type="email" name="email" value="<?= $form->email?>"></td>
    </tr>
    <tr>
        <td>Message:</td>
        <td><textarea name="message" id="" cols="30" rows="10"><?= $form->message?></textarea></td>
    </tr>
    <tr><td><button>Go</button></td></tr>

</form>
</table>
<?php



print_r($_POST);