<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?=MetaHelper::getTitle();?></title>
</head>
<body>
<h1>Admin Panel</h1>
<a href="/">Home</a>
<a href="/admin/books">Books</a>
<a href="/admin/book/add">Book add</a>
<a href="/admin/news_add">Add news</a>
<a href="/admin/docs/add">Add docs</a>
<a href="/logout">Logout</a>
<hr>


<?=$content ?>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<hr>
All rights reserved &copy; 1980 - <?=date('Y')?>
</body>
</html>